name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: code-correction-agent-poc
  REGION: asia-south1
  PROJECT_ID: agentic-trading-bot-469202

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          source: .
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          allow_unauthenticated: true
          env_vars: |
            GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            LANGSMITH_TRACING_V2=true
            LANGSMITH_ENDPOINT=https://api.smith.langchain.com
            LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }}
            LANGSMITH_PROJECT=${{ secrets.LANGSMITH_PROJECT }}

